objects/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>Master-Detail to find case to track time on</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Session Times</relationshipLabel>
    <relationshipName>Session_Times</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/fields/Session_Time__c.field-meta.xml
<CustomField>
    <fullName>Session_Time__c</fullName>
    <description>Retains each session Time</description>
    <label>Session Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session_Time__c.object
<CustomObject>
    <description>Keep track of every session and the time associated with it.</description>
    <label>Session Time</label>
    <nameField>
        <label>Session Time Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session Times</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aura/main/default/objects/Session_Time__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Field to the Agent</description>
    <label>Agent</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Session_Times</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Time__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Session Times</relationshipLabel>
    <relationshipName>Session_Times</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Time__c/fields/Case_Status__c.field-meta.xml
<CustomField>
    <fullName>Case_Status__c</fullName>
    <description>The status of the case at the time of this session.</description>
    <label>Case Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Time__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

aura/main/default/objects/Session_Time__c/fields/Manual_Entry__c.field-meta.xml
<CustomField>
    <fullName>Manual_Entry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manual Entry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CaseTimeCount.cls
global with sharing class CaseTimeCount {
    
    // Required for Managed packages to have a Namespace for custom fields/objects
    static String namespace = 'LWCCaseTimer__';
    @AuraEnabled
    // Checks all the required pre-config has been completed. 
    global static String checkAccess() {
        String accessMessage = null;
        
        // Check we can access the custom object
        Map<String,Schema.SObjectField> objMap = Schema.SObjectType.Session_Time__c.fields.getMap();
        String[] fieldsToCheck = new String[] {'Name',  namespace +'Case__c', namespace + 'Date__c', namespace + 'Duration__c', namespace + 'Agent__c', namespace + 'Case_Status__c', namespace + 'Manual_Entry__c',namespace + 'Comments__c' };
        for(String field : fieldsToCheck) {
            if(!objMap.get(field).getDescribe().isAccessible() && !objMap.get(field).getDescribe().isCreateable() ) {
                accessMessage = 'Unable to access Session Time object field ' + field;
                break;
            }
        }
        
        // Check we can access some related objects
        if (accessMessage == null && !Schema.sObjectType.Case.fields.Id.isAccessible()){
			accessMessage = 'Unable to access Case objects Id field.';
        }
        
        if (accessMessage == null && !Schema.sObjectType.User.fields.Name.isAccessible() && !Schema.sObjectType.User.fields.Id.isAccessible()){
			accessMessage = 'Unable to access the User objects Name field.';
        }
        
        return accessMessage;
    }
    
    @AuraEnabled
    // Called when the tab is closed to record time against the record.
    global static Session_Time__c newSession(Id caseId, Integer timeVal, String status) {
        // Time Calculations - convert milliseconds to seconds.   
        Integer timeInSecs = timeVal/1000;
        return CaseTimeCount.saveSession(caseId, timeInSecs, System.Date.today(), null, status, false);        
    }
    
    @AuraEnabled
    // Called when a new manual entry is saved
    global static Session_Time__c newSessionManual(Id caseId, String timeVal, String theDate, String comments, String status) {        
        // Split out the time string into hours, minutes and seconds
        String[] t = timeVal.split(':');
        Integer h = Integer.valueof(t[0]);
        Integer m = Integer.valueof(t[1]);
        Integer s = Integer.valueof(t[2]);
        Integer fullTime = s + (m * 60) + (h * 3600);
        
        return CaseTimeCount.saveSession(caseId, fullTime, Date.valueOf(theDate), comments, status, true);
    }
    
    global static Session_Time__c saveSession(Id caseId, Integer duration, Date theDate, String comments, String status, Boolean isManual)
    {   
        if (duration > 0)
        { 
            Session_Time__c session = new Session_Time__c();
            session.Case__c  = caseId;
            session.Date__c = theDate;
            session.Duration__c = duration;
            session.Agent__c = UserINFO.getUserId();
            session.Manual_Entry__c  = isManual;
            session.Comments__c = comments;
            session.Name = UserINFO.getName() + ' time of ' + duration + 's on ' + String.valueOf(session.Date__c);
            session.Case_Status__c = status;
            insert session;
            return session;
        }
        return null;
    }
    
    @AuraEnabled(cacheable=true)
    // Get all the sessions related to this record
    global static Session_Time__c[] grabSessions(Id recordId) {
        return [SELECT Id, Agent__r.Name , Agent__c, Date__c, Duration__c FROM Session_Time__c WHERE Case__c = :recordId ORDER BY CreatedDate DESC];
    }
    
    @AuraEnabled(cacheable=true)
    // Gets the total time spent on the record
    global static Double totalTime(Id recordId) {        
        AggregateResult aggr = [SELECT SUM(Duration__c) TotalDuration FROM Session_Time__c WHERE Case__c = :recordId][0];
        return aggr.get('TotalDuration') != null ? (Double)aggr.get('TotalDuration') : 0;
    }
    
}