force-app/main/default/objects/Session_Time__c.object
<CustomObject>
    <description>Keep track of every session and the time associated with it.</description>
    <label>Session Time</label>
    <nameField>
        <label>Session Time Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session Times</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aura/main/default/objects/Session_Time__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Field to the Agent</description>
    <label>Agent</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Session_Times</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Time__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Session Times</relationshipLabel>
    <relationshipName>Session_Times</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Time__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CaseTimeCountTest.cls
@isTest
global with sharing class CaseTimeCountTest {
    @testSetup
    static void setup() {
        Case c = new Case(Subject = 'Test Case');
        insert c;
        Session_Time__c s = new Session_Time__c (Case__c = c.Id, Date__c = System.Date.today(), Duration__c = 1200, Agent__c = UserInfo.getUserId());
        insert s;
        Session_Time__c s2 = new Session_Time__c (Case__c = c.Id, Date__c = System.Date.today(), Duration__c = 1988, Agent__c = UserInfo.getUserId());
        insert s2;
        c = new Case(Subject = 'Test Case 2');
        insert c;
    }
    
    static testMethod void checkAccessTest() {
        String message = CaseTimeCount.checkAccess();
        System.assert(message == null, 'Error checking access - message: ' + message);
    }
    
    static testMethod void newSessionTest() {
        Id cId = [SELECT Id FROM Case WHERE Subject='Test Case'].Id;
        Session_Time__c sesh = CaseTimeCount.newSession(cId, 120000, 'New');
        System.assert(sesh != null, 'Session not created properly.');
    }
    
    static testMethod void newSessionManualTest() {
        Id cId = [SELECT Id FROM Case WHERE Subject='Test Case'].Id;
        Session_Time__c sesh = CaseTimeCount.newSessionManual(cId, '00:05:30', '2022-03-16', 'Comments from Test Class', 'Working');
        System.assert(sesh != null, 'Manual Session not created properly.');
    }
    
    static testMethod void grabSessionsTest() {
        Id cId = [SELECT Id FROM Case WHERE Subject='Test Case'].Id;
        List<Session_Time__c> sesh = CaseTimeCount.grabSessions(cId);
        System.assert(!sesh.isEmpty(), 'List of Sessions not found');
    }
    
    static testMethod void totalTimeTest(){
        Id cId = [SELECT Id FROM Case WHERE Subject='Test Case'].Id;
        Double totalTimeVal = CaseTimeCount.totalTime(cId);
        System.assert(totalTimeVal == (1200 + 1988), 'Incorrect time returned - got: ' + totalTimeVal + ', expected: 3188'); 
        cId = [SELECT Id FROM Case WHERE Subject='Test Case 2'].Id;
        totalTimeVal = CaseTimeCount.totalTime(cId);
        System.assert(totalTimeVal == 0, 'Incorrect time returned - got: ' + totalTimeVal + ', expected: 0'); 
    }
    
}